// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEPHkm2DzMBMhospl6ipEJSqJakPeHZwM',
    appId: '1:787053705551:web:a07981f3bcc54857b0ad3a',
    messagingSenderId: '787053705551',
    projectId: 'konbusters',
    authDomain: 'konbusters.firebaseapp.com',
    storageBucket: 'konbusters.appspot.com',
    measurementId: 'G-6VEJC41HZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuEey460v-8mMK3R3dhW3y0wUTTXV_750',
    appId: '1:787053705551:android:d72889190dbae7afb0ad3a',
    messagingSenderId: '787053705551',
    projectId: 'konbusters',
    storageBucket: 'konbusters.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbHS7WRf-7SHF1VxTNw51fKjuALSzCGA0',
    appId: '1:787053705551:ios:0ab59e9fef5e8eb6b0ad3a',
    messagingSenderId: '787053705551',
    projectId: 'konbusters',
    storageBucket: 'konbusters.appspot.com',
    iosBundleId: 'com.example.sih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbHS7WRf-7SHF1VxTNw51fKjuALSzCGA0',
    appId: '1:787053705551:ios:691480519bd6a486b0ad3a',
    messagingSenderId: '787053705551',
    projectId: 'konbusters',
    storageBucket: 'konbusters.appspot.com',
    iosBundleId: 'com.example.sih.RunnerTests',
  );
}
  